#
# AzLink Bukkit config
#

# When enabled, vanished players will be ignored by AzLink: they won't be
# included in players count and won't receive commands while vanished.
# Try disabling this option if you have some issues.
ignore-vanished-players: false

# When enabled, new users registered with the AuthMe plugin will automatically be registered on the website
# WARNING: You need AuthMeReloaded version 5.6.0-beta2 or newer AND Azuriom version 1.0.0 or newer!
# If you are using multiples servers, you should use the same database for AuthMe to prevent users
# from registering multiple times
authme-integration: false

# When enabled, new users registered with the nLogin plugin will automatically be registered on the website
# WARNING: You need nLogin version 10.2.43 or newer!
# If you are using multiples servers, you should use the same database for nLogin to prevent users
# from registering multiple times
nlogin-integration: false

# When enabled, if SkinsRestorer is installed, and the SkinAPI plugin is present on the website,
# the player's skin will be updated to the website's skin
skinrestorer-integration: false

# When PlaceholderAPI is installed, AzLink will register some placeholders
# that can be used in the server.
placeholders:
  # By default, %azlink_money% is registered and can be used to get the player's money.
  # If the Shop plugin is installed on the website, you can enable the shop placeholders.
  # The available placeholders are listed on https://github.com/Azuriom/AzLink#shop-placeholders
  shop: false

  # If the vote plugin is installed on the website, you can enable the vote placeholders.
  # The available placeholders are listed on https://github.com/Azuriom/AzLink#vote-placeholders
  vote: false

  # Duration format with placeholders for hours, minutes, and seconds.
  # Use %H/%M/%S for zero-padded (e.g. 03, 12) and %h/%m/%s for non-padded (e.g. 3, 12).
  # Example: "%H:%M:%S" for "01:30:05", and "%h h %m m %s s" for "1 h 30 m 5 s".
  duration-format: "%H:%M:%S"

# Optional database-backed duplicate check to avoid HTTP 422 errors during registration.
# When enabled, AzLink will query the configured Azuriom database before attempting
# to create a new account through the API. If a record is found the registration is skipped
# and the player will be informed that their account already exists.
registration-check:
  enabled: false
  jdbc-url: "jdbc:mysql://localhost:3306/azuriom?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
  username: "azuriom"
  password: "change_me"
  table: "users"
  uuid-column: "game_id"
  username-column: "name"
  email-column: "email"

# Настройки HTTP-клиента для регистрации на сайте.
website:
  # Базовый URL API сайта без конечного слеша. Например: "https://example.com/api"
  url: "https://example.com/api"
  # Относительный путь для запроса регистрации. Значение по умолчанию: /register
  register-path: "/register"
  # Токен авторизации, который будет передан в заголовке Authorization.
  token: "change_me"
  # Секрет для формирования подписи запроса (HMAC-SHA256). Оставьте пустым, если подпись не требуется.
  signature-secret: ""
  timeouts:
    # Таймаут установки соединения (в миллисекундах).
    connect: 5000
    # Таймаут чтения ответа (в миллисекундах).
    read: 5000
  # Максимальное количество попыток при ошибках сервера или сетевых сбоях.
  max-retries: 3
  # Задержка между повторными попытками (в миллисекундах).
  retry-delay-ms: 1000
