name: AzLink
version: ${pluginVersion}
author: Azuriom Team
description: The plugin to link your Azuriom website with your server.
website: https://azuriom.com
main: com.azuriom.azlink.bukkit.AzLinkBukkitPlugin
api-version: 1.21
softdepend: [nLogin, PlaceholderAPI, SkinsRestorer]
loadbefore: [AuthMe]
bootstrapper: com.azuriom.azlink.bukkit.PluginBootstrapper
