name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        run: ./gradlew build

      - name: Upload AzLink.jar
        uses: actions/upload-artifact@v2
        with:
          name: AzLink
          path: universal/build/libs/AzLink-*.jar

      - name: Upload AzLink-Legacy.jar
        uses: actions/upload-artifact@v2
        with:
          name: AzLink-Legacy
          path: universal-legacy/build/libs/AzLink-Legacy-*.jar
