name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 1.8, 11 ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: AzLink
          path: universal/build/libs/AzLink.jar

      - uses: actions/upload-artifact@v2
        with:
          name: AzLink-Legacy
          path: universal-legacy/build/libs/AzLink-Legacy.jar
